### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by eloekset** [joeduffy/slice.net#9]
Both links to src/System.Slices and the design plan at master/docs/Span.md are now outdated. I browsed the corefxlab repo, but couldn't find the new locations to link to.

**Comment by joeduffy** [comment]
Thanks for letting me know.  It looks like the design doc moved to https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md (and offhand I'm unsure where the source code went).  I updated the README accordingly.
